[2023-08-30T19:58:08.437+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/sqlalchemy.py:124 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2023-08-30T19:58:08.445+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_migration.data_migration scheduled__2023-08-30T00:00:00+00:00 [queued]>
[2023-08-30T19:58:08.464+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_migration.data_migration scheduled__2023-08-30T00:00:00+00:00 [queued]>
[2023-08-30T19:58:08.465+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-08-30T19:58:08.475+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): data_migration> on 2023-08-30 00:00:00+00:00
[2023-08-30T19:58:08.479+0000] {standard_task_runner.py:57} INFO - Started process 280 to run task
[2023-08-30T19:58:08.482+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'data_migration', 'data_migration', 'scheduled__2023-08-30T00:00:00+00:00', '--job-id', '27', '--raw', '--subdir', 'DAGS_FOLDER/data_mig_dag.py', '--cfg-path', '/tmp/tmp2bs3j1lc']
[2023-08-30T19:58:08.485+0000] {standard_task_runner.py:85} INFO - Job 27: Subtask data_migration
[2023-08-30T19:58:08.500+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2023-08-30T19:58:08.534+0000] {task_command.py:415} INFO - Running <TaskInstance: data_migration.data_migration scheduled__2023-08-30T00:00:00+00:00 [running]> on host 86f9e97d6c70
[2023-08-30T19:58:08.546+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/sqlalchemy.py:124 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2023-08-30T19:58:08.600+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_migration' AIRFLOW_CTX_TASK_ID='data_migration' AIRFLOW_CTX_EXECUTION_DATE='2023-08-30T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-08-30T00:00:00+00:00'
[2023-08-30T19:58:08.607+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-08-30T19:58:08.609+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python /opt/***/dags/data_migration.py --connection postgresql+psycopg2://***:***@postgres/***']
[2023-08-30T19:58:08.618+0000] {subprocess.py:86} INFO - Output:
[2023-08-30T19:58:09.176+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2023-08-30T19:58:09.200+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=data_migration, task_id=data_migration, execution_date=20230830T000000, start_date=20230830T195808, end_date=20230830T195809
[2023-08-30T19:58:09.224+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-08-30T19:58:09.238+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-08-30T19:59:59.766+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/sqlalchemy.py:124 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2023-08-30T19:59:59.775+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_migration.data_migration scheduled__2023-08-30T00:00:00+00:00 [queued]>
[2023-08-30T19:59:59.783+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_migration.data_migration scheduled__2023-08-30T00:00:00+00:00 [queued]>
[2023-08-30T19:59:59.785+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-08-30T19:59:59.795+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): data_migration> on 2023-08-30 00:00:00+00:00
[2023-08-30T19:59:59.801+0000] {standard_task_runner.py:57} INFO - Started process 210 to run task
[2023-08-30T19:59:59.806+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'data_migration', 'data_migration', 'scheduled__2023-08-30T00:00:00+00:00', '--job-id', '2', '--raw', '--subdir', 'DAGS_FOLDER/data_mig_dag.py', '--cfg-path', '/tmp/tmpkwvimi5c']
[2023-08-30T19:59:59.809+0000] {standard_task_runner.py:85} INFO - Job 2: Subtask data_migration
[2023-08-30T19:59:59.824+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2023-08-30T19:59:59.871+0000] {task_command.py:415} INFO - Running <TaskInstance: data_migration.data_migration scheduled__2023-08-30T00:00:00+00:00 [running]> on host 3938d7abd9ff
[2023-08-30T19:59:59.886+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/sqlalchemy.py:124 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2023-08-30T19:59:59.949+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_migration' AIRFLOW_CTX_TASK_ID='data_migration' AIRFLOW_CTX_EXECUTION_DATE='2023-08-30T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-08-30T00:00:00+00:00'
[2023-08-30T19:59:59.958+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-08-30T19:59:59.960+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python /opt/***/dags/data_migration.py --connection postgresql+psycopg2://***:***@postgres/***']
[2023-08-30T19:59:59.972+0000] {subprocess.py:86} INFO - Output:
[2023-08-30T20:00:00.424+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2023-08-30T20:00:00.425+0000] {subprocess.py:93} INFO -   File "/opt/***/dags/data_migration.py", line 4, in <module>
[2023-08-30T20:00:00.426+0000] {subprocess.py:93} INFO -     from model import Connection
[2023-08-30T20:00:00.428+0000] {subprocess.py:93} INFO -   File "/opt/***/dags/model.py", line 5, in <module>
[2023-08-30T20:00:00.429+0000] {subprocess.py:93} INFO -     from geoalchemy2 import Geometry
[2023-08-30T20:00:00.430+0000] {subprocess.py:93} INFO - ModuleNotFoundError: No module named 'geoalchemy2'
[2023-08-30T20:00:00.447+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-08-30T20:00:00.462+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-08-30T20:00:00.467+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=data_migration, task_id=data_migration, execution_date=20230830T000000, start_date=20230830T195959, end_date=20230830T200000
[2023-08-30T20:00:00.487+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 2 for task data_migration (Bash command failed. The command returned a non-zero exit code 1.; 210)
[2023-08-30T20:00:00.506+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-08-30T20:00:00.524+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-08-30T20:27:27.067+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/sqlalchemy.py:124 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2023-08-30T20:27:27.078+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_migration.data_migration scheduled__2023-08-30T00:00:00+00:00 [queued]>
[2023-08-30T20:27:27.085+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_migration.data_migration scheduled__2023-08-30T00:00:00+00:00 [queued]>
[2023-08-30T20:27:27.087+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-08-30T20:27:27.096+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): data_migration> on 2023-08-30 00:00:00+00:00
[2023-08-30T20:27:27.100+0000] {standard_task_runner.py:57} INFO - Started process 247 to run task
[2023-08-30T20:27:27.103+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'data_migration', 'data_migration', 'scheduled__2023-08-30T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/data_mig_dag.py', '--cfg-path', '/tmp/tmpdgq4o9eq']
[2023-08-30T20:27:27.106+0000] {standard_task_runner.py:85} INFO - Job 3: Subtask data_migration
[2023-08-30T20:27:27.120+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2023-08-30T20:27:27.155+0000] {task_command.py:415} INFO - Running <TaskInstance: data_migration.data_migration scheduled__2023-08-30T00:00:00+00:00 [running]> on host 0a0db3a88e79
[2023-08-30T20:27:27.167+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/sqlalchemy.py:124 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2023-08-30T20:27:27.216+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_migration' AIRFLOW_CTX_TASK_ID='data_migration' AIRFLOW_CTX_EXECUTION_DATE='2023-08-30T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-08-30T00:00:00+00:00'
[2023-08-30T20:27:27.219+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-08-30T20:27:27.221+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python /opt/***/dags/data_migration.py --connection postgresql+psycopg2://***:***@postgres/***']
[2023-08-30T20:27:27.230+0000] {subprocess.py:86} INFO - Output:
[2023-08-30T20:27:27.824+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2023-08-30T20:27:27.825+0000] {subprocess.py:93} INFO -   File "/opt/***/dags/data_migration.py", line 4, in <module>
[2023-08-30T20:27:27.827+0000] {subprocess.py:93} INFO -     from model import Connection
[2023-08-30T20:27:27.828+0000] {subprocess.py:93} INFO -   File "/opt/***/dags/model.py", line 30, in <module>
[2023-08-30T20:27:27.829+0000] {subprocess.py:93} INFO -     class Traffic(Base):
[2023-08-30T20:27:27.831+0000] {subprocess.py:93} INFO -   File "/opt/***/dags/model.py", line 37, in Traffic
[2023-08-30T20:27:27.832+0000] {subprocess.py:93} INFO -     location = Column(Geometry(geometry_type='POINT', srid=4326, management=True))
[2023-08-30T20:27:27.833+0000] {subprocess.py:93} INFO - TypeError: __init__() got an unexpected keyword argument 'management'
[2023-08-30T20:27:27.881+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-08-30T20:27:27.894+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-08-30T20:27:27.899+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=data_migration, task_id=data_migration, execution_date=20230830T000000, start_date=20230830T202727, end_date=20230830T202727
[2023-08-30T20:27:27.921+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 3 for task data_migration (Bash command failed. The command returned a non-zero exit code 1.; 247)
[2023-08-30T20:27:27.965+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-08-30T20:27:27.980+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-08-30T20:33:05.686+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/sqlalchemy.py:124 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2023-08-30T20:33:05.696+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_migration.data_migration scheduled__2023-08-30T00:00:00+00:00 [queued]>
[2023-08-30T20:33:05.703+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_migration.data_migration scheduled__2023-08-30T00:00:00+00:00 [queued]>
[2023-08-30T20:33:05.705+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-08-30T20:33:05.714+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): data_migration> on 2023-08-30 00:00:00+00:00
[2023-08-30T20:33:05.719+0000] {standard_task_runner.py:57} INFO - Started process 218 to run task
[2023-08-30T20:33:05.722+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'data_migration', 'data_migration', 'scheduled__2023-08-30T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/data_mig_dag.py', '--cfg-path', '/tmp/tmpfei5u6zc']
[2023-08-30T20:33:05.725+0000] {standard_task_runner.py:85} INFO - Job 3: Subtask data_migration
[2023-08-30T20:33:05.740+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2023-08-30T20:33:05.775+0000] {task_command.py:415} INFO - Running <TaskInstance: data_migration.data_migration scheduled__2023-08-30T00:00:00+00:00 [running]> on host 961f38e8363e
[2023-08-30T20:33:05.792+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/sqlalchemy.py:124 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2023-08-30T20:33:05.844+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_migration' AIRFLOW_CTX_TASK_ID='data_migration' AIRFLOW_CTX_EXECUTION_DATE='2023-08-30T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-08-30T00:00:00+00:00'
[2023-08-30T20:33:05.847+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-08-30T20:33:05.849+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python /opt/***/dags/data_migration.py --connection postgresql+psycopg2://***:***@postgres/***']
[2023-08-30T20:33:05.858+0000] {subprocess.py:86} INFO - Output:
[2023-08-30T20:33:06.590+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2023-08-30T20:33:06.633+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=data_migration, task_id=data_migration, execution_date=20230830T000000, start_date=20230830T203305, end_date=20230830T203306
[2023-08-30T20:33:06.675+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-08-30T20:33:06.700+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-08-30T20:47:07.672+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/sqlalchemy.py:124 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2023-08-30T20:47:07.680+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_migration.data_migration scheduled__2023-08-30T00:00:00+00:00 [queued]>
[2023-08-30T20:47:07.687+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_migration.data_migration scheduled__2023-08-30T00:00:00+00:00 [queued]>
[2023-08-30T20:47:07.689+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-08-30T20:47:07.698+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): data_migration> on 2023-08-30 00:00:00+00:00
[2023-08-30T20:47:07.703+0000] {standard_task_runner.py:57} INFO - Started process 248 to run task
[2023-08-30T20:47:07.705+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'data_migration', 'data_migration', 'scheduled__2023-08-30T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/data_mig_dag.py', '--cfg-path', '/tmp/tmpkvbae4ar']
[2023-08-30T20:47:07.708+0000] {standard_task_runner.py:85} INFO - Job 3: Subtask data_migration
[2023-08-30T20:47:07.721+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2023-08-30T20:47:07.753+0000] {task_command.py:415} INFO - Running <TaskInstance: data_migration.data_migration scheduled__2023-08-30T00:00:00+00:00 [running]> on host 8f66711a2898
[2023-08-30T20:47:07.764+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/sqlalchemy.py:124 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2023-08-30T20:47:07.809+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_migration' AIRFLOW_CTX_TASK_ID='data_migration' AIRFLOW_CTX_EXECUTION_DATE='2023-08-30T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-08-30T00:00:00+00:00'
[2023-08-30T20:47:07.812+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-08-30T20:47:07.814+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python /opt/***/dags/data_migration.py --connection postgresql+psycopg2://***:***@postgres/***']
[2023-08-30T20:47:07.823+0000] {subprocess.py:86} INFO - Output:
[2023-08-30T20:47:08.228+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2023-08-30T20:47:08.247+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=data_migration, task_id=data_migration, execution_date=20230830T000000, start_date=20230830T204707, end_date=20230830T204708
[2023-08-30T20:47:08.293+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-08-30T20:47:08.306+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-08-30T21:06:35.299+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/sqlalchemy.py:124 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2023-08-30T21:06:35.310+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_migration.data_migration scheduled__2023-08-30T00:00:00+00:00 [queued]>
[2023-08-30T21:06:35.326+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_migration.data_migration scheduled__2023-08-30T00:00:00+00:00 [queued]>
[2023-08-30T21:06:35.331+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-08-30T21:06:35.353+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): data_migration> on 2023-08-30 00:00:00+00:00
[2023-08-30T21:06:35.363+0000] {standard_task_runner.py:57} INFO - Started process 220 to run task
[2023-08-30T21:06:35.366+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'data_migration', 'data_migration', 'scheduled__2023-08-30T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/data_mig_dag.py', '--cfg-path', '/tmp/tmpc6izepd5']
[2023-08-30T21:06:35.380+0000] {standard_task_runner.py:85} INFO - Job 3: Subtask data_migration
[2023-08-30T21:06:35.403+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2023-08-30T21:06:35.455+0000] {task_command.py:415} INFO - Running <TaskInstance: data_migration.data_migration scheduled__2023-08-30T00:00:00+00:00 [running]> on host cbc745b7550b
[2023-08-30T21:06:35.470+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/sqlalchemy.py:124 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2023-08-30T21:06:35.550+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_migration' AIRFLOW_CTX_TASK_ID='data_migration' AIRFLOW_CTX_EXECUTION_DATE='2023-08-30T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-08-30T00:00:00+00:00'
[2023-08-30T21:06:35.576+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-08-30T21:06:35.587+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python /opt/***/dags/data_migration.py --connection postgresql+psycopg2://***:***@postgres/***']
[2023-08-30T21:06:35.627+0000] {subprocess.py:86} INFO - Output:
[2023-08-30T21:06:36.163+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2023-08-30T21:06:36.185+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=data_migration, task_id=data_migration, execution_date=20230830T000000, start_date=20230830T210635, end_date=20230830T210636
[2023-08-30T21:06:36.210+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-08-30T21:06:36.228+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-08-30T21:16:08.247+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/sqlalchemy.py:124 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2023-08-30T21:16:08.257+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_migration.data_migration scheduled__2023-08-30T00:00:00+00:00 [queued]>
[2023-08-30T21:16:08.265+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_migration.data_migration scheduled__2023-08-30T00:00:00+00:00 [queued]>
[2023-08-30T21:16:08.266+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-08-30T21:16:08.275+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): data_migration> on 2023-08-30 00:00:00+00:00
[2023-08-30T21:16:08.280+0000] {standard_task_runner.py:57} INFO - Started process 277 to run task
[2023-08-30T21:16:08.283+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'data_migration', 'data_migration', 'scheduled__2023-08-30T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/data_mig_dag.py', '--cfg-path', '/tmp/tmp59ctct7v']
[2023-08-30T21:16:08.288+0000] {standard_task_runner.py:85} INFO - Job 3: Subtask data_migration
[2023-08-30T21:16:08.301+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2023-08-30T21:16:08.336+0000] {task_command.py:415} INFO - Running <TaskInstance: data_migration.data_migration scheduled__2023-08-30T00:00:00+00:00 [running]> on host 5b9f14bf20e0
[2023-08-30T21:16:08.349+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/sqlalchemy.py:124 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2023-08-30T21:16:08.398+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_migration' AIRFLOW_CTX_TASK_ID='data_migration' AIRFLOW_CTX_EXECUTION_DATE='2023-08-30T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-08-30T00:00:00+00:00'
[2023-08-30T21:16:08.401+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-08-30T21:16:08.402+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python /opt/***/dags/data_migration.py --connection postgresql+psycopg2://***:***@postgres/***']
[2023-08-30T21:16:08.412+0000] {subprocess.py:86} INFO - Output:
[2023-08-30T21:16:08.884+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2023-08-30T21:16:08.916+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=data_migration, task_id=data_migration, execution_date=20230830T000000, start_date=20230830T211608, end_date=20230830T211608
[2023-08-30T21:16:08.946+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-08-30T21:16:08.963+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
